/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clang_fq_FileQueueJNI */

#ifndef _Included_com_clang_fq_FileQueueJNI
#define _Included_com_clang_fq_FileQueueJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_clang_fq_FileQueueJNI_DE
#define com_clang_fq_FileQueueJNI_DE 1L
#undef com_clang_fq_FileQueueJNI_EN
#define com_clang_fq_FileQueueJNI_EN 2L
#undef com_clang_fq_FileQueueJNI_DE_XA
#define com_clang_fq_FileQueueJNI_DE_XA 3L
#undef com_clang_fq_FileQueueJNI_DE_XA_COMMIT
#define com_clang_fq_FileQueueJNI_DE_XA_COMMIT 4L
#undef com_clang_fq_FileQueueJNI_DE_XA_CANCEL
#define com_clang_fq_FileQueueJNI_DE_XA_CANCEL 5L
#undef com_clang_fq_FileQueueJNI_CLOSE
#define com_clang_fq_FileQueueJNI_CLOSE 9L
/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeRead
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeRead
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeWrite
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeWrite
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeReadXA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeReadXA
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeCommitXA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeCommitXA
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeCancelXA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeCancelXA
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeClose
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeGetMsgLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_clang_fq_FileQueueJNI_NativeGetMsgLength
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeUsage
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_clang_fq_FileQueueJNI_NativeUsage
  (JNIEnv *, jobject);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeMoveFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeMoveFQ
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeResetFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeResetFQ
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeFlushFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeFlushFQ
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeInfoFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeInfoFQ
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeSkipFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeSkipFQ
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeDiagFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeDiagFQ
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeCreateFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeCreateFQ
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_clang_fq_FileQueueJNI
 * Method:    NativeUnlinkFQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clang_fq_FileQueueJNI_NativeUnlinkFQ
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
